# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: audit-all-ids-files

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches: 
      - master
      - development
      - 1.0.x
      - 1.1.x
      - 2.0.x
  pull_request:
    branches: [ "*" ] # Run the workflow for all pull requests

jobs:
  check-test-cases:
    name: audit-all-ids-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run './RepositoryAutomation/build.cmd AuditAllIdsFiles'
        run: ./RepositoryAutomation/build.cmd AuditAllIdsFiles
